- hosts: green
  become: yes
  tasks:
    - name: Create a backup
      become: yes
      shell: tar -czvf /var/backups/nginx-backup.tar.gz -C /var/lib/nginx .

    - name: Fetch the backup
      fetch:
        src: //var/backups/nginx-backup.tar.gz
        dest: "{{ lookup('env', 'WORKSPACE') }}/previous/nginx-artifacts.tar.gz"
        flat: yes

    - name: Clean up the backup
      file:
        path: /var/backups//nginx-backup.tar.gz
        state: absent
