---
- hosts: blue
  become: yes
  tasks:
    - name: Stop Nginx service on blue servers
      service:
        name: nginx
        state: stopped
        enabled: no

    - name: Clean up old Nginx artifacts
      file:
        path: "/usr/local/nginx"
        state: absent
