---
- hosts: green
  become: yes
  vars:
    artifacts_path: "{{ lookup('env', 'WORKSPACE') }}/nginx-artifacts.tar.gz"
    nginx_dest: "/var/lib/nginx"
  tasks:
    - name: Ensure the destination directory exists
      file:
        path: "{{ nginx_dest }}"
        state: directory

    - name: Upload Nginx artifacts
      unarchive:
        src: "{{ artifacts_path }}"
        dest: "{{ nginx_dest }}"
        remote_src: no

    - name: Stop existing Nginx service if running
      become: yes
      service:
        name: nginx
        state: stopped

    - name: Start new Nginx service
      service:
        pattern: "{{ nginx_dest }}/objs/nginx"
        name: nginx
        state: started
      notify: Restart Nginx

  handlers:
    - name: Restart Nginx
      become: yes
      service:
        name: nginx
        state: restarted
