- hosts: loadbalancer
  become: yes
  tasks:
    - name: Switch traffic to Blue environment
      template:
        src: templates/nginx-blue.conf
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
