- hosts: loadbalancer
  become: yes
  tasks:
    - name: Switch traffic to Blue
      template:
        src: templates/nginx-blue.conf
        dest: /etc/nginx/nginx.conf
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
