---
- hosts: loadbalancer
  become: yes
  tasks:
    - name: Switch traffic to green servers
      template:
        src: "/path/to/templates/nginx-green.conf.j2"
        dest: "/etc/nginx/nginx.conf"
      notify: Reload Nginx

  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
